Cora:
  dim_hidden: 16
  weight_decay: 0.0005
  lr: 0.01
  dropout: 0.5
Citeseer:
  dim_hidden: 16
  weight_decay: 0.0005
  lr: 0.01
  dropout: 0.5
Pubmed:
  dim_hidden: 16
  weight_decay: 0.0005
  lr: 0.01
  dropout: 0.5
ogbn-arxiv:
  dim_hidden: 16
  weight_decay: 0.0005
  lr: 0.01
  dropout: 0.5
CoauthorPhysics:
  dim_hidden: 16
  weight_decay: 0.0005
  lr: 0.01
  dropout: 0.5
CoauthorCS:
  dim_hidden: 16
  weight_decay: 0.0005
  lr: 0.01
  dropout: 0.5
AmazonComputers:
  dim_hidden: 16
  weight_decay: 0.0005
  lr: 0.01
  dropout: 0.5
AmazonPhoto:
  dim_hidden: 16
  weight_decay: 0.0005
  lr: 0.01
  dropout: 0.5
TEXAS:
  dim_hidden: 16
  weight_decay: 0.0005
  lr: 0.01
  dropout: 0.5
WISCONSIN:
  dim_hidden: 16
  weight_decay: 0.0005
  lr: 0.01
  dropout: 0.5
CORNELL:
  dim_hidden: 16
  weight_decay: 0.0005
  lr: 0.01
  dropout: 0.5
ACTOR:
  dim_hidden: 16
  weight_decay: 0.0005
  lr: 0.01
  dropout: 0.5
